In [2]:
import numpy as dsa

In [3]:
dsa.__version__

'2.1.2'

In [4]:
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [5]:
arr1

array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [6]:
type(arr1)

numpy.ndarray

In [7]:
arr1.shape

(9,)

In [8]:
arr1[4]

np.int64(48)

In [9]:
arr1[1:4]

array([21, 32, 43])

In [10]:
arr1[1:4+1]

array([21, 32, 43, 48])

In [11]:
indices = [1, 2, 5, 6]

In [12]:
arr1[indices]

array([21, 32, 15, 76])

In [13]:
mask = (arr1 % 2 == 0)

In [14]:
mask

array([ True, False,  True, False,  True, False,  True, False, False])

In [15]:
arr1[0] = 100

In [16]:
arr1

array([100,  21,  32,  43,  48,  15,  76,  57,  89])

In [17]:
try:
    arr1[0] = 'Novo elemento'
except:
    print('Operação não permitida!')

Operação não permitida!


Funções no Numpy

In [18]:
arr2 = dsa.array([1, 2, 3, 4, 5])

In [19]:
arr2

array([1, 2, 3, 4, 5])

In [20]:
type(arr2)

numpy.ndarray

In [21]:
arr2.cumsum()

array([ 1,  3,  6, 10, 15])

In [22]:
arr2.cumprod()

array([  1,   2,   6,  24, 120])

In [23]:
arr3 = dsa.arange(0, 50, 5)

In [24]:
arr3

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [25]:
type(arr3)

numpy.ndarray

In [26]:
dsa.shape(arr3)

(10,)

In [27]:
arr3.dtype

dtype('int64')

In [28]:
arr4 = dsa.zeros(10)

In [29]:
arr4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [30]:
arr5 = dsa.eye(3)

In [31]:
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
arr6 = dsa.diag(dsa.array([1, 2, 3, 4]))

In [33]:
arr6

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [34]:
arr7 = dsa.array([True, False, False, True])

In [35]:
arr7

array([ True, False, False,  True])

In [36]:
arr8 = dsa.array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'])

In [37]:
arr8

array(['Linguagem Python', 'Linguagem R', 'Linguagem Julia'], dtype='<U16')

In [38]:
dsa.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [39]:
dsa.linspace(0, 10, 15)

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [40]:
dsa.logspace(0, 5, 10)

array([1.00000000e+00, 3.59381366e+00, 1.29154967e+01, 4.64158883e+01,
       1.66810054e+02, 5.99484250e+02, 2.15443469e+03, 7.74263683e+03,
       2.78255940e+04, 1.00000000e+05])

Matrizes

In [41]:
arr9 = dsa.array([[1, 2, 3], [4, 5, 6]])

In [42]:
type(arr9)

numpy.ndarray

In [43]:
arr9

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
arr9.shape

(2, 3)

In [45]:
arr10 = dsa.ones((2, 3))

In [46]:
print(arr10)

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
lista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

In [48]:
arr11 = dsa.matrix(lista)

In [49]:
arr11

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

In [50]:
type(arr11)

numpy.matrix

In [51]:
dsa.shape(arr11)

(3, 3)

In [52]:
arr11.size

9

In [53]:
arr11[2, 1]

np.int64(48)

In [54]:
arr11[0:2,2]

matrix([[22],
        [59]])

In [55]:
arr11[1,]

matrix([[ 0, 34, 59]])

In [56]:
arr11[1,0] = 100

In [57]:
arr11

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

In [58]:
x = dsa.array([1, 2])
y = dsa.array([1.0, 2.0])
z = dsa.array([1, 2], dtype = dsa.float64)

In [59]:
print(x.dtype, y.dtype, z.dtype)

int64 float64 float64


In [60]:
arr12 = dsa.array([[24, 76, 92, 14], [47, 35, 89, 2]], dtype = float)

In [61]:
arr12

array([[24., 76., 92., 14.],
       [47., 35., 89.,  2.]])

In [62]:
arr12.itemsize

8

In [63]:
arr12.nbytes

64

In [64]:
arr12.ndim

2

Analise Estatistica Basica com Numpy

In [65]:
arr14 = dsa.array([15, 23, 63, 94, 75])

In [67]:
#Média
dsa.mean(arr14)

np.float64(54.0)

In [68]:
#Desvio Padrão
dsa.std(arr14)

np.float64(30.34468652004828)

In [69]:
#Variancia
dsa.var(arr14)

np.float64(920.8)

Operações Matematicas com Arrays

In [70]:
arr15 = dsa.arange(1,10)

In [71]:
arr15

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
dsa.sum(arr15)

np.int64(45)

In [73]:
dsa.prod(arr15)

np.int64(362880)

In [74]:
dsa.cumsum(arr15)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [75]:
arr16 = dsa.array([3, 2, 1])
arr17 = dsa.array([1, 2, 3])

In [76]:
arr18 = dsa.add(arr16, arr17)

In [77]:
arr18

array([4, 4, 4])

In [78]:
arr19 = dsa.array([[1, 2], [3, 4]])
arr20 = dsa.array([[5, 6], [0, 7]])

In [79]:
arr19.shape

(2, 2)

In [80]:
arr20.shape

(2, 2)

In [81]:
arr19

array([[1, 2],
       [3, 4]])

In [82]:
arr20

array([[5, 6],
       [0, 7]])

In [83]:
arr21 = dsa.dot(arr19, arr20)

In [84]:
arr21

array([[ 5, 20],
       [15, 46]])

In [85]:
arr21 = arr19 @ arr20

In [86]:
arr21

array([[ 5, 20],
       [15, 46]])

In [87]:
arr21 = dsa.tensordot(arr19, arr20, axes = ((1), (0)))

In [88]:
arr21

array([[ 5, 20],
       [15, 46]])

Slicing(fatiamento) de Arrays

In [89]:
arr22 = dsa.diag(dsa.arange(3))

In [90]:
arr22

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 2]])

In [91]:
arr22[1, 1]

np.int64(1)

In [92]:
arr22[1]

array([0, 1, 0])

In [93]:
arr22[:, 2]

array([0, 0, 2])

In [95]:
arr23 = dsa.arange(10)

In [96]:
arr23

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
#[start:end:step]
arr23[2:9:3]

array([2, 5, 8])

In [99]:
a = dsa.array([1, 2, 3, 4])
b = dsa.array([4, 2, 2, 4])

In [100]:
a == b 

array([False,  True, False,  True])

In [101]:
dsa.array_equal(arr22, arr23)

False

In [102]:
arr23.min()

np.int64(0)

In [103]:
arr23.max()

np.int64(9)

In [104]:
dsa.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [105]:
arr24 = ([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [106]:
arr24

[1.2, 1.5, 1.6, 2.5, 3.5, 4.5]

In [107]:
arr25 = dsa.around(arr24)

In [108]:
arr25

array([1., 2., 2., 2., 4., 4.])

In [110]:
arr26 = dsa.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [111]:
arr26

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [114]:
#"Achatando" a matriz
arr27 = arr26.flatten()

In [115]:
arr27

array([1, 2, 3, 4, 5, 6, 7, 8])

In [116]:
arr28 = dsa.array([1, 2, 3])

In [117]:
arr28

array([1, 2, 3])

In [118]:
dsa.repeat(arr28, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [119]:
dsa.tile(arr28, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [120]:
arr29 = dsa.array([5, 6])

In [121]:
arr30 = dsa.copy(arr29)

In [122]:
arr30

array([5, 6])